### ISSUE TITLE
cell type specific  covariance matrices 

### ISSUE THREAD

**Issue by jayypaul** [JiayuSuPKU/Smoother#2]
Hello,

Very interesting paper and tool!

I have a question about this part of the code in quadratic_loss():

else: # use different spatial weight matrices for different cell types
		neg_loglik = ((beta.unsqueeze(1) @ inv_cov @ beta.unsqueeze(2)).squeeze() * group_scales).sum()

My interpretation is that there might be benefit to using cell type specific spatial weight matrices and thus covariance matrices? Any tips on how to properly use this idea for imputation and how it might affect the results? 

My thoughts are that different cell types will have different autocorrelation decay constants (rho's) based on their respective cell type densities, and that this may be able to be tuned with a prior and thus may also require a cell type specific weight matrix? 

Not sure if that's right but hoping to get your thoughts on this. Thanks!

**Comment by JiayuSuPKU** [comment]
Thank you and yes, the `group_scales` parameter is designed to provide cell-type-specific regularization scales, which is by default set to one for all groups.

Similar to the global regularization strength $\lambda$ (e.g. [`lambda_spatial_loss` in the deconvolution model](https://github.com/JiayuSuPKU/Smoother/blob/444ee7720288573e9c1308216ea60b23f97eb2d9/smoother/models/deconv.py#L112)), `group_scales` here is also interpreted as the inverse variance of the multivariate normal prior. The larger the prior variance (i.e. smaller scales), the weaker the regularization will be. It is different from the $\rho$ parameter which sets the decay rate and intuitively controls the "size of spatial pattern". Smaller $\rho$ s give more local focus. If $\rho = 0$, spots will only care about themselves. Another way of thinking is that $\rho$ is a spectral property related to a spatial graph (closer to the `k` in a knn graph), while $\lambda$ and 'group_scales' reflect the strength of belief that the prior graph can explain the data.

Because of the interchangeability between $\lambda$ and `group_scales`, it is usually enough to just tune $\lambda$ unless you really want to have cell-type-specific regularization. Our empirical results also suggest that `group_scales` do not add much to the performance. We kept it in place mainly because sometime people want to "protect" minor populations from being diluted (i.e. setting `group_scales` to zero). We do have a function ([SpatialLoss.estimate_confidence](https://github.com/JiayuSuPKU/Smoother/blob/444ee7720288573e9c1308216ea60b23f97eb2d9/smoother/losses.py#L216C2-L216C72)) that estimates the per-group scale using a simple linear regression deconvolution model. The scale is set to be proportional to the variance of estimated cell-type abundance. In other contexts, you may also consider the variance of marker gene expression per cell type. 

On the impact of cell-type-specific $\rho$, it's possible to build different graphs/weight matrices for different cell types when initializing the SpatialLoss object. The `group_scales`(i.e. `SpatialLoss.confidences`) can then be updated manually. We haven't formally test the effect of heterogenous $\rho$ s. My guess is that it will be quite similar to the effect of `group_scales` and wouldn't make substantial change in terms of general performance.

**Comment by jayypaul** [comment]
Hi Jiayu Su,

Thank you for your detailed insight, it really helps me understand your method. 

As for the estimate_confidence, this seems to require a bulk expression signature, aka a geneset per expected cell type present? Provided in the format: ref_exp = num_gene x num_group, but most cases a cell type geneset signature will be of varying length.. Could you provide a comment on how to effectively use this? 

Thanks for your correspondence.

Best,

Jordan

**Comment by JiayuSuPKU** [comment]
Hi Jordan,

`estimate_confidence` essentially learns the variance of cell-type abundance and scales cell types accordingly. The intuition is that the abundance of major cell types will have larger variability just by chance (var = np(1-p)) from a simple binomial model), and thus may require stronger regularization. Minor cell types not detected in most area will have smaller variances and thus won't be smoothed out. To estimate the abundance, `estimate_confidence` runs a simple non-spatial deconvolution which requires the reference expression of all marker genes in all cell types.

If you assume that your signature already gives a good sense of cell-type abundance (e.g. using IG gene expression as a proxy of B cell abundance), then you can simply set `SpatialLoss.confidences` to the (weighted) variance of (weighted) gene expression signature across spots. More generally, there is no right or wrong approach for this since we are designing the *prior knowledge* on the data. `SpatialLoss.confidences` can be quite arbitrary as long as you have good understanding of why some cell types should be more regularized than others. In some extreme contexts such as the peripheral blood, there may not even be any spatial structure. The prior is eventually irrelevant if the signal in the data is strong enough. 

Hope this helps!

Best,
Jiayu

**Comment by jayypaul** [comment]
Thanks alot Jiayu, this makes a lot of sense. I'll give it a try!

Best,

Jordan
